### ISSUE TITLE
Add support for application name

### ISSUE THREAD

**Issue by aliberty** [apprenda/apprenda-jenkins-integration#1]
Currently the plugin only supports supplying an application alias.  It would be very useful to be able to provide an application name along with the alias.

**Comment by dutronlabs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jenkins - add support for application name](https://trello.com/c/odGl8exh/243-jenkins-add-support-for-application-name)

**Comment by michmike** [comment]
@aliberty  this will is done and will be delivered with 2.0 release this week
![image](https://user-images.githubusercontent.com/6655749/31882935-a655dde2-b7e8-11e7-8d5e-c6c6f17a3e03.png)
