### ISSUE TITLE
Parameterize deploy parameters

### ISSUE THREAD

**Issue by markpiersak** [apprenda/apprenda-jenkins-integration#2]
Currently, it appears we cannot pass in parameters for the values in the build job.  We would like to use parameters from our ci/cd pipeline reference up stream MultiJob parameters.

**Comment by michmike** [comment]
hi @markpiersak can you please elaborate on this request?

**Comment by markpiersak** [comment]
Sure,

Inside of Jenkins, the Apprenda Build configuration, you must input 'literal' values.  We would like to be able to use 'parameters', ie: $appName, $artifactName, etc..

The reason being is that we'd like to re-use the jenkins jobs for other app deployments, and from a centralized template.  For example, we would have a Jenkins 'MultiJob' that calls an Apprenda Deploy, and passes in the parameters to the Apprenda Deploy job.

**Comment by michmike** [comment]
hi @markpiersak thanks for the reply. Is it fair to assume you are using the Jenkins "multijob" plugin as well? there are other plugins as well like the "Parameterized Trigger Plugin", etc.

Are the parameters going to be stored in temporary variables, or do you use environment variables as well

**Comment by michmike** [comment]
Implemented in such a way that we can consume data from environment variables that exist in the build step. The documentation of this plugin has all the data

**Comment by markpiersak** [comment]
Thanks!  This is exactly what we were looking for.
