### ISSUE TITLE
"Force Deployment to Specific Version" does not work.

### ISSUE THREAD

**Issue by markpiersak** [apprenda/apprenda-jenkins-integration#3]
When checking this box in the Plugin and specifying a version, the setting does not stick after saving the job configuration.

**Comment by markpiersak** [comment]
We'd like this ability, plus, the ability to inject Environment Variables to the Version.

**Comment by michmike** [comment]
@markpiersak, you can inject environment variables to WCF services using the apprenda manifest. so that becomes part of your archive building process versus part of the Jenkins deploy job.
let me know if i misunderstood what you meant by environment variables here

**Comment by michmike** [comment]
completed with the version 2.0 release.
