### ISSUE TITLE
getting below error while deplying from jenkins to apprenda

### ISSUE THREAD

**Issue by roshvin** [apprenda/apprenda-jenkins-integration#8]
Unable to serialize com.apprenda.jenkins.plugins.apprenda.ApprendaBuilder$1@2cedf14
ERROR: [APPRENDA] IO Exception: Unable to serialize com.apprenda.jenkins.plugins.apprenda.ApprendaBuilder$1@2cedf14
Finished: FAILUR

**Comment by michmike** [comment]
I am closing this issue as i believe your team was able to get past it. if not, let us know and we will investigate.
