### ISSUE TITLE
Using Parameters in Plugin Requires $ in Parameter Setup/Config

### ISSUE THREAD

**Issue by markpiersak** [apprenda/apprenda-jenkins-integration#9]
This is a minor issue, but it appears in order for this plugin to resolve Jenkins parameters, we must create the parameter 'Name' with a leading $.  This is unique in that the parameter Name setup should be just a string w/o the $.  We expect to only use $ if we are trying to resolve the parameter in the Jenkins configuration.

**Comment by michmike** [comment]
$ApprendaStage is the only parameter that requires to have a fixed name. For every other parameter you can pick the name and any prefix/postfix you want to use.

**Comment by markpiersak** [comment]
I've tested by adding in my own parameters for say, the alias, and they
would not resolve until I added the $.

**Comment by michmike** [comment]
hi @markpiersak  i believe we resolved this issue over email. thanks!
